export const AMENITY_PRESETS = [
  { slug: "private-pool", labelEn: "Private pool", labelTh: "สระว่ายน้ำส่วนตัว", icon: "pool" },
  { slug: "kids-pool", labelEn: "Children's pool", labelTh: "สระเด็ก", icon: "pool" },
  { slug: "plunge-pool", labelEn: "Plunge pool", labelTh: "สระจุ่ม", icon: "pool" },
  { slug: "jacuzzi", labelEn: "Jacuzzi", labelTh: "จากุซซี่", icon: "bath" },
  { slug: "hot-tub", labelEn: "Hot tub", labelTh: "อ่างน้ำร้อน", icon: "bath" },
  { slug: "wifi", labelEn: "High-speed Wi-Fi", labelTh: "Wi-Fi ความเร็วสูง", icon: "wifi" },
  { slug: "workspace", labelEn: "Workspace", labelTh: "พื้นที่ทำงาน", icon: "workspace" },
  { slug: "air-conditioning", labelEn: "Air conditioning", labelTh: "เครื่องปรับอากาศ", icon: "airConditioning" },
  { slug: "heating", labelEn: "Heating", labelTh: "เครื่องทำความร้อน", icon: "heating" },
  { slug: "parking", labelEn: "Private parking", labelTh: "ที่จอดรถส่วนตัว", icon: "parking" },
  { slug: "free-parking", labelEn: "Free parking", labelTh: "ที่จอดรถฟรี", icon: "parking" },
  { slug: "elevator", labelEn: "Elevator", labelTh: "ลิฟต์", icon: "elevator" },
  { slug: "kitchen", labelEn: "Equipped kitchen", labelTh: "ครัวพร้อมอุปกรณ์", icon: "kitchen" },
  { slug: "dishwasher", labelEn: "Dishwasher", labelTh: "เครื่องล้างจาน", icon: "dishwasher" },
  { slug: "refrigerator", labelEn: "Refrigerator", labelTh: "ตู้เย็น", icon: "refrigerator" },
  { slug: "coffee-machine", labelEn: "Coffee machine", labelTh: "เครื่องชงกาแฟ", icon: "coffee" },
  { slug: "outdoor-dining", labelEn: "Outdoor dining", labelTh: "พื้นที่รับประทานอาหารกลางแจ้ง", icon: "dining" },
  { slug: "bbq", labelEn: "BBQ area", labelTh: "พื้นที่บาร์บีคิว", icon: "grill" },
  { slug: "karaoke", labelEn: "Karaoke", labelTh: "คาราโอเกะ", icon: "karaoke" },
  { slug: "sound-system", labelEn: "Sound system", labelTh: "ระบบเสียง", icon: "soundSystem" },
  { slug: "smart-tv", labelEn: "Smart TV", labelTh: "สมาร์ททีวี", icon: "tv" },
  { slug: "tv-cable", labelEn: "TV & cable", labelTh: "ทีวีและเคเบิล", icon: "tv" },
  { slug: "netflix", labelEn: "Netflix", labelTh: "Netflix", icon: "netflix" },
  { slug: "projector", labelEn: "Projector", labelTh: "โปรเจกเตอร์", icon: "projector" },
  { slug: "games", labelEn: "Games", labelTh: "เกมและกิจกรรม", icon: "games" },
  { slug: "pool-table", labelEn: "Pool table", labelTh: "โต๊ะพูล", icon: "poolTable" },
  { slug: "gym", labelEn: "Gym", labelTh: "ห้องออกกำลังกาย", icon: "gym" },
  { slug: "bicycle", labelEn: "Bicycle", labelTh: "จักรยาน", icon: "bicycle" },
  { slug: "beachfront", labelEn: "Beachfront", labelTh: "ติดชายหาด", icon: "beachfront" },
  { slug: "beach-access", labelEn: "Beach access", labelTh: "ทางลงหาด", icon: "beachfront" },
  { slug: "sea-view", labelEn: "Sea view", labelTh: "วิวทะเล", icon: "seaView" },
  { slug: "balcony", labelEn: "Balcony", labelTh: "ระเบียง", icon: "terrace" },
  { slug: "garden", labelEn: "Garden", labelTh: "สวน", icon: "garden" },
  { slug: "outdoor-shower", labelEn: "Outdoor shower", labelTh: "ฝักบัวกลางแจ้ง", icon: "outdoorShower" },
  { slug: "pet-friendly", labelEn: "Pet friendly", labelTh: "นำสัตว์เลี้ยงเข้าพักได้", icon: "pet" },
  { slug: "laundry", labelEn: "Laundry", labelTh: "ซักรีด", icon: "laundry" },
  { slug: "washer", labelEn: "Washer", labelTh: "เครื่องซักผ้า", icon: "laundry" },
  { slug: "washing-machine", labelEn: "Washing machine", labelTh: "เครื่องซักผ้า", icon: "laundry" },
  { slug: "iron", labelEn: "Iron", labelTh: "เตารีด", icon: "iron" },
  { slug: "hair-dryer", labelEn: "Hair dryer", labelTh: "ไดร์เป่าผม", icon: "hairDryer" },
  { slug: "safe", labelEn: "Safe", labelTh: "ตู้เซฟ", icon: "safe" },
  { slug: "security", labelEn: "24-hour security", labelTh: "รปภ. 24 ชั่วโมง", icon: "security" },
  { slug: "cctv", labelEn: "CCTV", labelTh: "กล้องวงจรปิด", icon: "cctv" },
  { slug: "fire-extinguisher", labelEn: "Fire extinguisher", labelTh: "ถังดับเพลิง", icon: "fireExtinguisher" },
  { slug: "first-aid", labelEn: "First aid kit", labelTh: "ชุดปฐมพยาบาล", icon: "firstAid" },
] as const;
